[package]
name = "dexios"
version = "7.4.9"
authors = ["brxken128 <brxken128@tutanota.com>"]
readme = "README.md"
edition = "2021"
description = "Secure, fast and authenticated command-line encryption of files with modern ciphers and an audited encryption backend."
keywords = ["encryption", "utility", "file", "command-line", "secure"]
categories = ["cryptography", "command-line-utilities"]
rust-version = "1.57"
repository = "https://github.com/brxken128/dexios"
homepage = "https://github.com/brxken128/dexios"
documentation = "https://github.com/brxken128/dexios/wiki"
license = "BSD-2-Clause"

# this is for sites other than crates.io, who may still use it
[badges]
maintenance = { status = "actively-developed" }

[dependencies]
aes-gcm = { version = "0.9.4", features = ["stream"] }
clap = { version = "3.1.18", features = ["cargo"] }
anyhow = "1.0.57"
rand = "0.8.5"
rpassword = "6.0.1"
argon2 = "0.4.0"
blake3 = "1.3.1"
secrecy = "0.8.0"
chacha20poly1305 = { version = "0.9.0", features = ["stream"] }
aead = "0.4.3"
zip = { version = "0.6.2", features = ["bzip2"] }